### ISSUE TITLE
Service account secret not automatically generated

### ISSUE THREAD

**Issue by kekbur** [palimarium/istio-vault-ca#5]
Since Kubernetes 1.24 [a secret is no longer automatically generated when a service account is created](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes). The guide in [cert-manager-setup.md](https://github.com/palimarium/istio-vault-ca/blob/master/cert-manager-setup.md) should be updated with instructions to create the secrets manually:

```
cat <<EOF | kubectl --context="${CTX_CLUSTER_XXX}" apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: vault-issuer
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
EOF
```

This also removes the need to capture the secret's name in `ISSUER1_SECRET_REF` and `ISSUER2_SECRET_REF`.
